params:
  epochs:1
  batch_size:32
  no_classes:10
  input_shape:[28,28]
  loss_function:sparce_categorical_cross_entropy
  metrices:accuracy
  optimizer:adam
  validation_data:500


artifacts:
  artifacts_dir:artifacts
  model_dr:model
  plots_dir:plots
  checkpoint_dir:checkpoints

logs:
  logs_dir:logs_dir
  general_logs:general_logs
  tensorboard_logs:tensorboard_logs